language: go

go:
  - 1.19.x
  - 1.20.x

services:
  - docker

script:
  - docker pull confluentinc/confluent-local:7.4.1
  - docker pull confluentinc/cp-schema-registry:7.4.1
  - go build cmd/ccloud-schema-exporter/ccloud-schema-exporter.go
  - cd cmd/integrationTests
  - go test
  - cd ../internals
  - go test

addons:
  sonarcloud:
    organization: "abraham-leal"
