language: go

go:
  - 1.15.x
  - 1.16.x

services:
  - docker

script:
  - docker pull confluentinc/cp-zookeeper:6.1.0
  - docker pull confluentinc/cp-server:6.1.0
  - docker pull confluentinc/cp-schema-registry:6.1.0
  - go build cmd/ccloud-schema-exporter/ccloud-schema-exporter.go
  - cd cmd/integrationTests
  - docker-compose up -d
  - go test
  - cd ../internals
  - docker-compose -f ../integrationTests/docker-compose-internal.yml up -d
  - go test

addons:
  sonarcloud:
    organization: "abraham-leal"