language: go

go:
  - 1.17.x
  - 1.18.x

services:
  - docker

script:
  - docker pull confluentinc/cp-zookeeper:7.1.1
  - docker pull confluentinc/cp-server:7.1.1
  - docker pull confluentinc/cp-schema-registry:7.1.1
  - go build cmd/ccloud-schema-exporter/ccloud-schema-exporter.go
  - cd cmd/integrationTests
  - docker-compose up -d
  - go test
  - cd ../internals
  - go test

addons:
  sonarcloud:
    organization: "abraham-leal"
