{
 "title": "Schema Exporter Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Garbage Collection Time (Seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\"}",
     "legendFormat": "Duration 100%"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\"}",
     "legendFormat": "Duration 75%"
    }
   ]
  },
  {
   "title": "Number of GoRoutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Schema Exporter Memory Usage (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Memory Allocated to Heap" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "Total In Use" }
   ]
  },
  {
   "title": "Memory Consumption Per Second (Bytes/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[1m])",
     "legendFormat": "Memory Consumption"
    }
   ]
  }
 ]
}